//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanFlowApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Details
    {
        public Details()
        {
            this.Operations = new HashSet<Operations>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Operations> Operations { get; set; }
    }
}
