//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanFlowApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public int Id { get; set; }
        public Nullable<int> DetailId { get; set; }
        public Nullable<int> TypeOperationId { get; set; }
        public Nullable<int> EstimatedTime { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> DoneQuantity { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> AssignedWorkerId { get; set; }
    
        public virtual Details Details { get; set; }
        public virtual Workers Workers { get; set; }
        public virtual OperationStatuses OperationStatuses { get; set; }
        public virtual TypeOperation TypeOperation { get; set; }
    }
}
